version: '3.7'
services:
  elasticsearch-hot:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    build: .
    environment:
      - node.name=elasticsearch-hot
      - cluster.name=es-docker-cluster
      #- node.attr.size=hot
      - node.attr.box_type=hot
      - discovery.seed_hosts=elasticsearch-warm,elasticsearch-cold
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm,elasticsearch-cold
      - node.roles=master,data_content,data_hot
      - path.repo=/usr/share/elasticsearch/snapshots
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - hot_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - 9200:9200
    networks:
      - elastic
    
    deploy:
      replicas: 2
 
  elasticsearch-warm:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    build: .
    environment:
      - node.name=elasticsearch-warm
      - cluster.name=es-docker-cluster
      #- node.attr.size=warm
      - node.attr.box_type=warm
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-cold
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm,elasticsearch-cold
      - node.roles=master,data_warm
      - path.repo=/usr/share/elasticsearch/snapshots
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - warm_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - elastic
    deploy:
      replicas: 1
 
  elasticsearch-cold:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    build: .
    environment:
      - node.name=elasticsearch-cold
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-warm
      - node.attr.box_type=cold
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm,elasticsearch-cold
      - node.roles=master,data_cold
      - path.repo=/usr/share/elasticsearch/snapshots
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    volumes:
      - cold_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - elastic
    deploy:
      replicas: 1
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-hot:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-hot:9200","http://elasticsearch-warm:9200","http://elasticsearch-cold:9200"]'
    networks:
      - elastic
 
volumes:
  hot_data:
    driver: local
  warm_data:
    driver: local
  cold_data:
    driver: local
  snapshots:
    driver: local
 
networks:
  elastic:
    driver: overlay
